### ISSUE TITLE
How do I add get a team data folder or add new staff to our existing team's data folder?

### ISSUE THREAD

**Issue by staceypark** [lzim/mtl#114]
You can request a team data folder or add new staff to existing team folders by going to be added going to mtl.how/data, and clicking on "Request New Team Folder" or "Request Team Membership Change" at the top and filling out the form.

![image](https://user-images.githubusercontent.com/31089501/77801703-9b0bad00-7036-11ea-887d-0b0e0e99df67.png)

**Comment by lzim** [comment]
Closing this reference to _MTL 2.0_
No longer our workflow with _Modeling to Learn 3.0_
